### ISSUE TITLE
Merge the browser and the server compiler

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/compiler#1]
I would like to merge the compiler in one single script removing the circular `riot` dependency exporting all the methods we want to use in `riot` and also in `riot-cli`

**Comment by GianlucaGuarini** [comment]
@aMarCruz I am trying to make a standalone version of the riot compiler, but it seems that it relies on the `brackets` method of `riot-tmpl` do you think it makes sense to make a new module called `riot-utils` where brackets and other common function could be shared?

cc @cognitom @tipiirai

**Comment by aMarCruz** [comment]
I think no.
The Functionality of brackets is inherent to the compiler, that is, it should be because it is designed to work with .tag files, not tmpl, right?
I was thinking about include optional precompiled expressions too, so tmpl would be a lighter and more efficient version, and we don't need brackets for that, but the current brackets default is poor election for efficient parsing. **Internally**, it would be better to use something like `{@ @}` --including invalid characters for js (with current defaults, one is never sure that a string that includes these have really an expression).

The hard work must be done by the compiler, not riot.tag or tmpl, so we must put restrictions with clear rules to what users can put in riot.tag() or evaluate with tmpl() --we don't have a parser, expressions must be simple and clear, as so the format of the html paramneter of riot.tag().
I will write part of this rules for discussion, later, and think about how we can benefit riot production version without impact backward compatibility ...too much.

**Comment by aMarCruz** [comment]
Btw, I reviewed tmpl. The error is in the test. It is unsynced with the new version. Anyway, I find one or two errors. I'm busy now, but I will post the PR tonight.

**Comment by GianlucaGuarini** [comment]
Ok I will let you work on `riot-compiler` and `riot-tmpl`, I have prepared you the environment for both. Just ping me when you are done and I will include/test both in `riot` branch `2.3.0`. Once you will have these modules ready I could prepare the `riot-cli` to use the compiler via command line.

**Comment by aMarCruz** [comment]
ok, thank you.

**Comment by aMarCruz** [comment]
@GianlucaGuarini , one more thing:
I would like to add this restrictions to expressions passed to tmpl (i.e. with riot.tag or direct evaluation):
1) Comments are not allowed.
2) Whitespace characteres `\r` and `\n` must be escaped.
3) Literal regexps must be enclosed in parentheses without spaces between parentheses and slashes.

The compiler is responsible for removing comments and escape EOLs in .tag files, and prepare the regexps for tmpl. Thus, the work is not duplicated and the size of the version without the compiler is reduced.
What do you think?

cc @tipiirai

**Comment by tipiirai** [comment]
All the points (1, 2 and 3) make perfect sense to me.

**Comment by GianlucaGuarini** [comment]
@aMarCruz it sounds great, please let me know when you are ready for a beta release.
I think you need to make public some compiler methods to let me run it through `riot-cli`.
