### ISSUE TITLE
compile() browser vs server difference

### ISSUE THREAD

**Issue by nippur72** [riot/compiler#29]
I don't know if it's intended to be so, but I noticed a minor difference between compiler in the browser and in the server:

```JavaScript
// on the server
var arr = compiler.compile(template, {entities: true})

// on the browser it needs an extra parameter
var arr = compiler.compile(template, true, {entities: true})  
```

**Comment by aMarCruz** [comment]
gotcha! @nippur72 , the `riot.compile` function in the browser have many overloads, and it is not the same function as `compile` in the nodejs version. This causes confusion.

The first call in your post is equivalent to browser [`riot.compile(tag)`](http://riotjs.com/api/compiler/#compile-tag). The second form is equivalent to [`riot.compile(tag, true)`](http://riotjs.com/api/compiler/#compile-to-str).
Both return the same result, but the first call executes the tag and an error is generated because riot (`globalEval`) does not expect a parameter of type object.

Now, the compiler options (`{entitites: true}` in this case) is an additional parameter for all the `riot.compile` overloads in the browser, but you're right, the `true` parameter makes no sense. I will correct this in the next update.

**Comment by nippur72** [comment]
What's the reason behind having different code between client and server? As I imagine it, they should be the same, but perhaps I'm missing something.

**Comment by aMarCruz** [comment]
@nippur72 , it was the original design, and I have to maintain backward compatibility.
Unfortunatelly, in the case of `riot.compile(tag [, true])`, the parameter to not running the compiled tag is `true`, so I can't omit it. `opts` is an additional parameter which allow code like this:
```
var notrun = riot.compile(tag_str, true, {type:"babel"})
var runned = riot.compile(tag_str, {type:"babel"})
```
however:
```
var notrun = riot.compile(tag_str, true, {type:"babel", entities:true})  // OK
var runned = riot.compile(tag_str, {type:"babel", entities:true})  // ERROR!
```

**Comment by nippur72** [comment]
Uhm, that leaves me more confused than before :smile:. Anyway since I managed to make it work both on client and server, that's fine with me.

**Comment by aMarCruz** [comment]
Yeah, it is confusing. I will write about this in the guide ...some day :)
