### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by ghost** [riot/compiler#53]
Should #we create a CONTRIBUTING.md file as seen in riot/riot?

**Comment by aMarCruz** [comment]
@rodrigorodriguez maybe it is not necessary. doc/guide.md is not for insertion in the main riot docs, the info could be confusing to users in general. I started it as a guide of changes for developers of riot tools and to get summary info for doc/README.md. The doc/README.md is the file that should update the main riot docs [here](https://github.com/riot/riot.github.io/blob/master/guide/compiler.md) and [here](https://github.com/riot/riot.github.io/blob/master/api/compiler.md), but I have neglected it because lack of time and my bad English.

I'm preparing API docs from the JSDoc comments in the code for developers, but doc/README for general users needs heavy work of someone capable. If you can help with this it would be great!
Thanks.

**Comment by rodrigorodriguez** [comment]
I am not a native speaker, as I live in Brazil the pt-br is my native language. But I think that your English is not bad at all.
Maybe CONTRIBUTING.md would contain just the basic on a section 'Contributing to Riot.js Compiler' I felt it would be necessary when I was trying to update the docs. Sure it was my first commit as PR to a project, but it can happen to someone else. 
At least, it would contain a link to the riot CONTRIBUTING.md, containg the PR guidelines for example at a start.
About the additional files, sure! I will take some time to read them carefully, and try to write a little. 
Anyway, if you can clarify https://github.com/riot/riot/issues/1492#issuecomment-179555061 regarding the creation of branches and PR (that topic would be the first on CONTRIBUTING.md) I would start updating GUIDE.md and then get ready to send updates.

**Comment by GianlucaGuarini** [comment]
The source code is really straight forward, add a feature create a test for it and make a PR. I don't think we need a CONTRIBUTING.md file for this repo.
Thanks for the idea anyways
